force-app/main/default/objects/QuestionAndAnswers__c/QuestionAndAnswers__c.object-meta.xml
<CustomObject>
    <label>QuestionAndAnswer</label>
    <nameField>
        <label>Nombre de QuestionAndAnswers</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QuestionsAndAnswers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuestionAndAnswers__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QuestionsAndAnswers</relationshipLabel>
    <relationshipName>QuestionsAndAnswers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuestionAndAnswers__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <label>Form</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FORMCONF_REGISTRATION_FORM_2</fullName>
                <label>FORMCONF REGISTRATION FORM 2</label>
            </value>
            <value>
                <fullName>FORMCONF_REGISTRATION_FORM_1</fullName>
                <label>FORMCONF REGISTRATION FORM 1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TypeIntegrationAuraController.cls
public with sharing class TypeIntegrationAuraController {
        @AuraEnabled(cacheable=true)
        public static List<QuestionAndAnswers__c> getAnswers(Id recordId, String searchText) {
            string sTempSearchKey = '%' + searchText + '%';
            if (String.isBlank(searchText))
                return [
                    SELECT Question__c, Answer__c,Form__c
                    FROM QuestionAndAnswers__c
                    WHERE Account__c = :recordId
                    WITH SECURITY_ENFORCED
                ];
            else {
                return [
                    SELECT Question__c, Answer__c,Form__c
                    FROM QuestionAndAnswers__c
                    WHERE Account__c = :recordId AND (Answer__c LIKE :sTempSearchKey OR Question__c LIKE :sTempSearchKey)
                    WITH SECURITY_ENFORCED
                ];

            }
        }
}